AllCops:
  NewCops: enable
  TargetRubyVersion: 3.0.X

Layout/LineLength:
  Max: 120

Style/Documentation:
  Enabled: false

Naming/MethodParameterName:
  AllowedNames:
    - as

Metrics/MethodLength:
  Exclude:
    - 'test/**/*.rb'
